### ISSUE TITLE
Question: Are train (21 GB), valid (1.2 GB), and test (1.6 GB) of B-F-H 2D Keypoints clips* (frontal view) whole set of How2Sign?

### ISSUE THREAD

**Issue by CHRIBUR0309** [how2sign/how2sign.github.io#1]
Or subset (other subset will be added)?

**Comment by how2sign** [comment]
Hi, @CHRIBUR0309!
Yes, those are the complete set of the clips (not the entire video).

I realized that my explanation about that in the download section was not clear and updated it as well.

Thank you,

**Comment by CHRIBUR0309** [comment]
I'm sorry but I still cannot understand....

The set of the clips != the entire video set?
The clips are made from original How2 and the video set contains ASL video, right?

**Comment by how2sign** [comment]
Correct! 
The set of clips are the parts of the entire video that has a corresponding annotation (e.g English Translation, Gloss annotation, 2D Keypoints etc...). 
The clips are sentence-level segments of the entire video. Note that the difference in sizes is because not the whole video contains a corresponding English translation. In addition, we also compressed the videos to make them easier to distribute.

**Comment by CHRIBUR0309** [comment]
I see....

So, when I try SLT, I can do that with just pose estimation data on the web page and How2's English text, right?
